name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [13.x]
    name: eslint check
    steps:
        # Check-out repository under GitHub workspace
        # https://github.com/actions/checkout
      - uses: actions/checkout@v2
        # Step's name
      - name: Use Node.js ${{ matrix.node-version }}
        # Configures the node version used on GitHub-hosted runners
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v1
        # The Node.js version to configure
        with:
          node-version: ${{ matrix.node-version }}
        # Add environment variables
      - name: npm install
        # Install and build project
        run: |
          make install
        env:
          CI: true
      - name: Run linter
        # Run Linter
        run: |
          make lint